@startuml
!include ../../lib/header.puml

!procedure $drawConnections()
!endprocedure

'import / export / void markers
!procedure $drawMarkers()
!endprocedure

'-----------Draw Diagram Section---------------------------------
title
    Gregtech New Horizons 2.3.4
    enriched naquadah processing line
endtitle

$drawMachines("naquadria.json")
$drawConnections()
$drawMarkers()

@enduml