@startuml
!include ../../lib/header.puml

!procedure $drawConnections()
   po2 --> pi3
   po4 --> pi5
   po5 --> pi6
   po8 --> pi8
   po6 --> pi9
   po12 --> pi12
   po16 ..> pi9
   po11 -left..> pi7
!endprocedure

'import / export / void markers
!procedure $drawMarkers()
!endprocedure

'-----------Draw Diagram Section---------------------------------
title
    Gregtech New Horizons 2.3.4
    naquadria processing line
endtitle

$drawMachines("naquadria.json")
$drawConnections()
$drawMarkers()

@enduml