@startuml
scale 1
'skinparam linetype polyline
'skinparam linetype ortho
left to right direction
' tier style
skinparam rectangle {
    BackgroundColor<<MV>> #82BEDF
    BackgroundColor<<HV>> #ADABBC
    BackgroundColor<<EV>> #D79DE4
    BackgroundColor<<IV>> #625D98
    BackgroundColor<<ZPM>> #979797
}
<style>
    title {
        HorizontalAlignment center
    }
</style>
' line styles for marking input/output
!$fromMainStorageStyle = "#green;line.dotted;text:green"
!$fromMainStorage = %string($fromMainStorageStyle+" : import")
!$backToMainStorageStyle = "#blue;line.dotted;text:blue"
!$backToMainStorage = %string($backToMainStorageStyle+" : export")
!$voidedStyle = "#red;line.dotted;text:red"
!$voided = %string($voidedStyle+" : void")
!$toProcessStyle = "#orange;line.dotted;text:orange"
!$toProcess = %string($voidedStyle+" : process")
left header
<font color=black>source:</font> https://github.com/pavel-belous/GTNH-PlantUML
endheader
@enduml