@startuml
!include ../../lib/header.puml

!procedure $drawConnections()
   po4 ---> pi5
   po5 --> pi6
   po6 ..> pi2
   po7 --> pi7
   po3 --> pi9
'   po --> pi
'   po --> pi
'   po --> pi
'   po --> pi
'   po --> pi
'   po --> pi
'   po --> pi
'   po --> pi
'   po --> pi
'   po --> pi
'   po --> pi
'   po --> pi
'   po --> pi
'   po --> pi
'   po --> pi
'   po --> pi
'   po --> pi
'   po --> pi
'   po --> pi
'   po --> pi
'   po --> pi
'   po --> pi
'   po --> pi
'   po --> pi
'   po --> pi
!endprocedure

'-----------Draw Diagram Section---------------------------------
title
    Gregtech New Horizons 2.3.4
    enriched naquadah processing line
endtitle

$drawMachines("enriched-naquadah.json")
$drawConnections()

@enduml